### ISSUE TITLE
Migrate master files from ODF to something plaintext file format

### ISSUE THREAD

**Issue by piroor** [clear-code/firefox-support-common#1]
Currently the format of master files are ODF (ODT and ODS.) It is hard to be diff-ed. We should use something plain text format as the master instead of such binary format.

Plan:

 * Markdown or reStructuredText
 * Pandoc: convert the source to ODS

In the source we are using many numbers of connected cells. The migrated file must keep those cells.

**Comment by myokoym** [comment]
ASAP :fire:

**Comment by myokoym** [comment]
:memo: 検証手順書は最終的にPDFになればよいので、電子出版系のツールを使えばできそう。

**Comment by myokoym** [comment]
[pandocブランチ]で作業中です。
