### ISSUE TITLE
現行アドオン廃止後の設定シート作成

### ISSUE THREAD

**Issue by piroor** [clear-code/firefox-support-common#11]
customization-items.odsの内容のうち、WebExtensionsベースの拡張機能でもその他の手段でも実現できないものは廃止とする。何らかの方法で実現可能なものは、そのように記載する。

**Comment by piroor** [comment]
Security-8, Security-9で`about:*`の無効化に使用しているアドオンは、WebExtensions非対応である。WebExtensionsベースで実現可能かどうか調査が必要。

**Comment by piroor** [comment]
Tab-5-2で使用するアドオン「newtab.url」を代替する方法の調査が必要

**Comment by piroor** [comment]
一通りの情報は埋めた

**Comment by fujimotos** [comment]
マイグレーション済みなのでクローズ。
