### ISSUE TITLE
Markdownに移行した検証手順書の入力フィールドだった部分を変数にする

### ISSUE THREAD

**Issue by myokoym** [clear-code/firefox-support-common#3]
>
課題としては、LibreOffice Writer上で入力フィールドを使っていた部分が展開されてしまっており、Firefoxのバージョンなどの変更が面倒になってしまっているという問題があります。
>
次のフェーズで、ERBなどのテンプレートの導入を検討しようと思っています。
>
https://github.com/clear-code/firefox-support-common/pull/2

GitHubでのプレビューを考えて、拡張子は`.md`のままで`<%= ... %>`を埋め込む方針。
値はひとまずRakefileベタ書きでよいか。

**Comment by cosmo0920** [comment]
ERBだとRubyとかなり紐付いてしまうのでMustacheはどうでしょうか？
Mustacheであればいろんな言語の実装があるのでより多くの人が読み書きできます。

**Comment by myokoym** [comment]
おお、これですね。

* [drubyコラム: Mustache (定型文書の生成とERB)](https://gist.github.com/seki/1194969)

今回はRubyのコードを書く必要がないですし、シンプルになってよさそうなので検討してみます。ありがとうございます。

**Comment by myokoym** [comment]
> 値はひとまずRakefileベタ書きでよいか。

いまの仕組みだとRakefileがRakeのruleの監視対象になっていないので、.mdを更新せずにRakefile内の値だけを更新すると、`rake pdf`でのPDF生成がスキップされてしまう。事前に`rake clobber`すればいいんだけど、少し不便。

**Comment by myokoym** [comment]
ref: a555b7ec30ce8cb125b37fc4e4ddbda4a8ad9fde

**Comment by myokoym** [comment]
> 
いまの仕組みだとRakefileがRakeのruleの監視対象になっていないので、.mdを更新せずにRakefile内の値だけを更新すると、`rake pdf`でのPDF生成がスキップされてしまう。事前に`rake clobber`すればいいんだけど、少し不便。

できた https://github.com/clear-code/firefox-support-common/commit/3f980b0b425950c551fe4dc8eb9a7edbbb92b744

**Comment by myokoym** [comment]
https://github.com/clear-code/firefox-support-common/commit/06a4980d21cf0c79c1ee7fac97b3180b7e876677 で対応しました。
