### ISSUE TITLE
verification_manual.mdをgithubで表示したときにurlがおかしくなっている

### ISSUE THREAD

**Issue by lv7777** [clear-code/firefox-support-common#4]
https://github.com/clear-code/firefox-support-common/blob/master/verification_manual/verification_manual.md#672-%E6%BA%96%E5%82%99

を開いたときにhttpのリンクが、後ろの文字とくっついて、リンクを開いたときにnot foundと表示されてしまいます。

例：Firefoxのロケーションバーに「https://itisatrap.org/firefox/its-an-attack.html」と入力し、Enterを押下する。  

environment: firefox38,windows10

**Comment by piroor** [comment]
マージしました。ありがとうございます！
