### ISSUE TITLE
設定シートをテキストベースの管理に移行するか検討する

### ISSUE THREAD

**Issue by myokoym** [clear-code/firefox-support-common#6]
検証手順書の移行は #1 、 #3 で実施したが、設定シートの移行は未実施。

移行方法だけでなく、そもそも移行するべきかどうかについても検討する。
設定シートは現在の仕組みでも差分が見られる（編集後に手動でCSVにエクスポートしているため）ので、移行が難しいなら見送るのも有力。

**Comment by myokoym** [comment]
* 最終成果物がPDFではなくExcelかODSのためPandocは使えなそう
  * Rubyのライブラリなどを使えば生成できそう
      * [RailsでExcelを扱うGemまとめ - Qiita](http://qiita.com/Kta-M/items/02a2c41c5624f75498aa)
      * 今より管理しやすくなるかは疑問

**Comment by fujimotos** [comment]
Firefox 68.0esrから設定シートをテキストで管理するようになった。
実現されているのでクローズ。
